"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class NavStatus(object):
    __slots__ = ["nav_state_name", "completed_wps", "total_wps"]

    def __init__(self):
        self.nav_state_name = ""
        self.completed_wps = 0
        self.total_wps = 0

    def encode(self):
        buf = BytesIO()
        buf.write(NavStatus._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __nav_state_name_encoded = self.nav_state_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__nav_state_name_encoded)+1))
        buf.write(__nav_state_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ii", self.completed_wps, self.total_wps))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != NavStatus._get_packed_fingerprint():
            raise ValueError("Decode error")
        return NavStatus._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = NavStatus()
        __nav_state_name_len = struct.unpack('>I', buf.read(4))[0]
        self.nav_state_name = buf.read(__nav_state_name_len)[:-1].decode('utf-8', 'replace')
        self.completed_wps, self.total_wps = struct.unpack(">ii", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if NavStatus in parents: return 0
        tmphash = (0xacb79a079bc247) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if NavStatus._packed_fingerprint is None:
            NavStatus._packed_fingerprint = struct.pack(">Q", NavStatus._get_hash_recursive([]))
        return NavStatus._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

